version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates managed by GitHub Actions once a month
      interval: "monthly"
    groups:
      # Group together all dependencies in a single pull request
      dependencies:
        patterns:
          - "*"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      # Check for updates managed by npm once a month
      interval: "monthly"
    groups:
      # Group together all dependencies in a single pull request
      dependencies:
        patterns:
          - "*"
    ignore:
       # https://github.com/francoismassart/eslint-plugin-tailwindcss/issues/325
       - dependency-name: "tailwindcss"

  # Maintain dependencies for Composer
  - package-ecosystem: "composer"
    directory: "/server"
    schedule:
      # Check for updates managed by Composer once a month
      interval: "monthly"
    groups:
      # Group together all dependencies in a single pull request
      dependencies:
        patterns:
          - "*"
