name: raven-url-shortener

services:
    # https://hub.docker.com/_/redis
    redis:
        image: redis:alpine
        restart: always
        command: >
            --requirepass ${REDIS_PASSWORD} --maxmemory 128mb --maxmemory-policy allkeys-lru
        volumes:
            - ./server/docker/services/redis:/usr/local/etc/redis
        healthcheck:
            test: redis-cli --raw incr ping
            retries: 3
            timeout: 5s
        ports:
            - "6379:${REDIS_PORT}"

    # https://hub.docker.com/_/postgres
    postgres:
        image: postgres:alpine
        restart: always
        volumes:
            - ./server/docker/services/postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USERNAME}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        healthcheck:
            test: pg_isready --dbname=${DATABASE_NAME} --username=${DATABASE_USERNAME}
            retries: 3
            timeout: 5s
        ports:
            - "5432:${DATABASE_PORT}"

    # https://hub.docker.com/r/dpage/pgadmin4/
    pgadmin:
        image: dpage/pgadmin4:latest
        restart: always
        volumes:
            - ./server/docker/services/pgadmin:/var/lib/pgadmin
        depends_on:
            - postgres
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
        healthcheck:
            test: wget -O - http://localhost
            retries: 3
            timeout: 5s
        ports:
            - "8080:80"

    # https://github.com/FlorianLeChat/Raven-Url-Shortener
    node:
        image: raven-url-shortener-frontend
        restart: always
        volumes:
            - ./client/logs:/usr/src/app/logs
        command: npm run start
        depends_on:
            - php
        healthcheck:
            test: wget -O - http://localhost:3000
            retries: 3
            timeout: 5s
        build:
            context: ./client
            dockerfile: ./docker/scripts/Dockerfile
        ports:
            - "3000:3000"

    # https://github.com/FlorianLeChat/Raven-Url-Shortener
    php:
        image: raven-url-shortener-backend
        restart: always
        volumes:
            - ./server/logs:/var/www/html/var/log
        command: ./docker/scripts/production/entrypoint.sh
        depends_on:
            - redis
            - postgres
        environment:
            - WAIT_HOSTS=redis:${REDIS_PORT}, postgres:${DATABASE_PORT}
        healthcheck:
            test: curl -f http://localhost:8000/
            retries: 3
            timeout: 5s
        build:
            context: ./server
            dockerfile: ./docker/scripts/production/Dockerfile
        ports:
            - "8000:8000"