name: raven-url-shortener

services:
    cache:
        image: valkey/valkey:8
        command: >
            --requirepass ${CACHE_PASSWORD}
            --maxmemory 128mb
            --maxmemory-policy allkeys-lru
        volumes:
            - valkey_data:/data
        environment:
            TZ: ${APP_TIMEZONE}
        healthcheck:
            test: valkey-cli --raw incr ping
            retries: 3
            timeout: 5s
            start_period: 30s

    database:
        image: postgres:18
        volumes:
            - postgres_data:/var/lib/postgresql/18/docker
        environment:
            TZ: ${APP_TIMEZONE}
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USERNAME}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        healthcheck:
            test: pg_isready --dbname=${DATABASE_NAME} --username=${DATABASE_USERNAME}
            retries: 3
            timeout: 5s
            start_period: 30s

    docs:
        image: swaggerapi/swagger-ui:latest
        depends_on:
            server:
                condition: service_healthy
        environment:
            URL: http://server:8000/openapi.json
        healthcheck:
            test: wget -O - http://127.0.0.1:8080/
            retries: 3
            timeout: 5s
            start_period: 30s
        ports:
            - "8080:8080"

    server:
        image: raven-url-shortener-backend
        command: docker/scripts/development/entrypoint.sh
        volumes:
            - ./server:/var/www/html:cached
            - /var/www/html/.git
            - /var/www/html/vendor
            - /var/www/html/var
            - /var/www/html/node_modules
        depends_on:
            cache:
                condition: service_healthy
            database:
                condition: service_healthy
        extra_hosts:
            - "host.docker.internal:host-gateway"
        healthcheck:
            test: curl -f http://localhost:8000/
            retries: 3
            timeout: 5s
            start_period: 30s
        build:
            target: development
            context: ./server
            dockerfile: ./docker/Dockerfile
        ports:
            - "8000:8000"

volumes:
    valkey_data:
    postgres_data:
