name: raven-url-shortener

services:
    # https://hub.docker.com/_/redis
    redis:
        image: redis:8
        restart: always
        command: >
            --requirepass ${REDIS_PASSWORD} --maxmemory 128mb --maxmemory-policy allkeys-lru
        volumes:
            - ./server/docker/services/cache:/usr/local/etc/redis
        healthcheck:
            test: redis-cli --raw incr ping
            retries: 3
            timeout: 5s
        expose:
            - "${REDIS_PORT}"

    # https://hub.docker.com/_/postgres
    postgres:
        image: postgres:18
        restart: always
        volumes:
            - ./server/docker/services/database:/var/lib/postgresql/18/docker
        environment:
            TZ: ${APP_TIMEZONE}
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USERNAME}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        healthcheck:
            test: pg_isready --dbname=${DATABASE_NAME} --username=${DATABASE_USERNAME}
            retries: 3
            timeout: 5s
        expose:
            - "${DATABASE_PORT}"

    # https://hub.docker.com/r/dpage/pgadmin4/
    pgadmin:
        image: dpage/pgadmin4:9
        restart: always
        volumes:
            - ./server/docker/services/pgadmin:/var/lib/pgadmin
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
        healthcheck:
            test: wget -O - http://localhost
            retries: 3
            timeout: 5s
        ports:
            - "8080:80"

    # https://hub.docker.com/r/swaggerapi/swagger-ui
    swagger:
        image: swaggerapi/swagger-ui:latest
        depends_on:
            php:
                condition: service_healthy
        environment:
            URL: https://url.florian-dev.fr/api/swagger.json
        healthcheck:
            test: wget -O - http://127.0.0.1:8080
            retries: 3
            timeout: 5s
        ports:
            - "8081:8080"

    # https://hub.docker.com/_/varnish
    varnish:
        image: varnish:8-alpine
        volumes:
            - ./client/docker/configuration/default.vcl:/etc/varnish/default.vcl:ro
        depends_on:
            node:
                condition: service_healthy
        environment:
            VARNISH_SIZE: 128m
        healthcheck:
            test: wget -O - http://localhost/
            retries: 3
            timeout: 5s
        ports:
            - "80:80"

    # https://github.com/FlorianLeChat/Raven-Url-Shortener
    node:
        image: raven-url-shortener-frontend
        restart: always
        command: ./docker/scripts/entrypoint.sh
        depends_on:
            php:
                condition: service_healthy
        environment:
            TZ: ${APP_TIMEZONE}
        healthcheck:
            test: wget -O - http://localhost:3000
            retries: 3
            timeout: 5s
        build:
            context: ./client
            dockerfile: ./docker/scripts/Dockerfile
        expose:
            - "3000"

    # https://github.com/FlorianLeChat/Raven-Url-Shortener
    php:
        image: raven-url-shortener-backend
        restart: always
        command: ./docker/scripts/production/entrypoint.sh
        volumes:
            - ./server/logs:/var/www/html/logs
        depends_on:
            redis:
                condition: service_healthy
            postgres:
                condition: service_healthy
        environment:
            TZ: ${APP_TIMEZONE}
        healthcheck:
            test: curl -f http://127.0.0.1:9000/ 2>&1 | grep "Connection reset by peer"
            retries: 3
            timeout: 5s
        build:
            context: ./server
            dockerfile: ./docker/scripts/production/Dockerfile
        ports:
            - "9000:9000"