name: raven-url-shortener

services:
    # https://hub.docker.com/_/redis
    redis:
        image: redis:8
        command: >
            --requirepass ${REDIS_PASSWORD} --maxmemory 128mb --maxmemory-policy allkeys-lru
        volumes:
            - ./server/docker/services/cache:/usr/local/etc/redis
        healthcheck:
            test: redis-cli --raw incr ping
            retries: 3
            timeout: 5s
        expose:
            - "${REDIS_PORT}"

    # https://hub.docker.com/_/postgres
    postgres:
        image: postgres:18
        volumes:
            - ./server/docker/services/database:/var/lib/postgresql/18/docker
        environment:
            TZ: ${APP_TIMEZONE}
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USERNAME}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        healthcheck:
            test: pg_isready --dbname=${DATABASE_NAME} --username=${DATABASE_USERNAME}
            retries: 3
            timeout: 5s
        expose:
            - "${DATABASE_PORT}"

    # https://hub.docker.com/r/dpage/pgadmin4/
    pgadmin:
        image: dpage/pgadmin4:9
        volumes:
            - ./server/docker/services/pgadmin:/var/lib/pgadmin
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            PGADMIN_LISTEN_PORT: 8080
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
            PGADMIN_CONFIG_SERVER_MODE: "False"
            PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
        healthcheck:
            test: wget -O - http://localhost:8080/
            retries: 3
            timeout: 5s
        ports:
            - "8080:8080"

    # https://hub.docker.com/r/swaggerapi/swagger-ui
    swagger:
        image: swaggerapi/swagger-ui:latest
        depends_on:
            php:
                condition: service_healthy
        environment:
            URL: http://localhost:8000/api/swagger.json
        healthcheck:
            test: wget -O - http://127.0.0.1:8080/
            retries: 3
            timeout: 5s
        ports:
            - "8081:8080"

    # https://github.com/FlorianLeChat/Raven-Url-Shortener
    php:
        image: raven-url-shortener-backend
        command: ./docker/scripts/development/entrypoint.sh
        develop:
            watch:
                - path: ./server
                  action: sync
                  target: /var/www/html
                  ignore:
                    - vendor/
                - path: ./server/composer.lock
                  action: rebuild
        volumes:
            - ./server/logs:/var/www/html/logs
        depends_on:
            redis:
                condition: service_healthy
            postgres:
                condition: service_healthy
        environment:
            TZ: ${APP_TIMEZONE}
        healthcheck:
            test: curl -f http://localhost:8000/
            retries: 3
            timeout: 5s
        build:
            context: ./server
            dockerfile: ./docker/scripts/development/Dockerfile
        ports:
            - "8000:8000"