framework:
    secret: "%env(APP_SECRET)%"
    session:
        cookie_samesite: lax

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file

when@prod:
    framework:
        http_cache: true