framework:
    mailer:
        dsn: smtp://%env(SMTP_USERNAME)%:%env(SMTP_PASSWORD)%@%env(SMTP_HOST)%:%env(SMTP_PORT)%
        envelope:
            sender: "%env(SMTP_USERNAME)%"
        headers:
            From: "Raven Url Shortener <%env(SMTP_USERNAME)%>"