#when prod
framework:
    rate_limiter:
        read_api:
            limit: 50
            policy: "sliding_window"
            interval: "1 minute"
            cache_pool: raven_cache_pool
        write_api:
            limit: 5
            policy: "sliding_window"
            interval: "1 minute"
            cache_pool: raven_cache_pool