parameters:
    app.timezone: "%env(APP_TIMEZONE)%"
    app.smtp_enabled: "%env(SMTP_ENABLED)%"
    app.smtp_user: "%env(SMTP_USERNAME)%"
    app.dkim_enabled: "%env(DKIM_ENABLED)%"
    app.dkim_domain: "%env(DKIM_DOMAIN)%"
    app.dkim_selector: "%env(DKIM_SELECTOR)%"
    app.dkim_private_key: "%env(DKIM_PRIVATE_KEY)%"
    .container.dumper.inline_factories: true

services:
    App\:
        exclude:
            - "../src/Kernel.php"
            - "../src/Domain/Entity/"
            - "../src/DependencyInjection/"
        resource: "../src/"
    _defaults:
        autowire: true
        autoconfigure: true
    App\Infrastructure\EventListener\RequestListener:
        tags: [kernel.event_listener]
    App\Infrastructure\EventListener\ExceptionListener:
        tags: [kernel.event_listener]