services:
    App\:
        exclude:
            - "../src/Domain/Entity/"
            - "../src/Kernel.php"
            - "../src/DependencyInjection/"
        resource: "../src/"
    _defaults:
        autowire: true
        autoconfigure: true