services:
    App\:
        exclude:
            - "../src/Kernel.php"
            - "../src/Domain/Entity/"
            - "../src/DependencyInjection/"
        resource: "../src/"
    _defaults:
        autowire: true
        autoconfigure: true
    App\Infrastructure\EventListener\ExceptionListener:
        tags: [kernel.event_listener]