name: Docker Image CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron: 0 6 * * 1
  pull_request:
  workflow_dispatch:

jobs:
  codeql:
    uses: ./.github/workflows/codeql.yml

  symfony:
    uses: ./.github/workflows/symfony.yml

  eslint:
    uses: ./.github/workflows/eslint.yml

  build-image:
    runs-on: ubuntu-latest
    needs: [ codeql, symfony, eslint ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta for Front-end image
        id: client-meta
        uses: docker/metadata-action@v5
        with:
          flavor: latest=true
          images: ghcr.io/${{ github.repository }}-website
          tags: |
            type=sha
      - name: Docker meta for Back-end image
        id: server-meta
        uses: docker/metadata-action@v5
        with:
          flavor: latest=true
          images: ghcr.io/${{ github.repository }}-api
          tags: |
            type=sha
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Front-end Docker Image and push
        uses: docker/build-push-action@v6
        with:
          file: ./client/docker/scripts/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.client-meta.outputs.tags }}
          labels: ${{ steps.client-meta.outputs.labels }}
          context: ./client
      - name: Build Back-end Docker Image and push
        uses: docker/build-push-action@v6
        with:
          file: ./server/docker/scripts/development/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.server-meta.outputs.tags }}
          labels: ${{ steps.server-meta.outputs.labels }}
          context: ./server
