name: Symfony

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    strategy:
      matrix:
        php-version: [ 8.2, 8.3, 8.4 ]
      fail-fast: false
    steps:
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
    - name: Checkout
      uses: actions/checkout@v5
    - name: Set Composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
    - name: Cache Composer packages
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
        path: ${{ steps.composer-cache.outputs.dir }}
        restore-keys: ${{ runner.os }}-composer-
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Create database and load fixtures
      run: |
        mkdir -p var
        touch var/data.db
        php bin/console --env=test doctrine:schema:create --no-interaction
        php bin/console --env=test doctrine:fixtures:load --no-interaction
    - name: Warm up Symfony cache
      run: php bin/console cache:warmup --no-interaction
    - name: Run PHP Code Sniffer
      run: vendor/bin/phpcs -s
    - name: Run PHPStan
      run: vendor/bin/phpstan analyse --error-format=github
    - name: Run PHP Mess Detector
      run: vendor/bin/phpmd ./src github phpmd.xml.dist
    - name: Execute tests with PHPUnit
      run: vendor/bin/phpunit
